### ISSUE TITLE
installing with npm

### ISSUE THREAD

**Issue by sladwig** [GaiAma/cuid-cli#2]
I tried to install it with npm, but didn't work...

    ➜  npm -g install @gaiama/cuid-cli
    /usr/local/Cellar/node/9.5.0/bin/cuid -> /usr/local/Cellar/node/9.5.0/lib/node_modules/@gaiama/cuid-cli/index.js
    + @gaiama/cuid-cli@1.0.5
    added 52 packages from 12 contributors in 36.397s
    ➜  cuid
    zsh: command not found: cuid

not even after restarting shell and am using npm 5.7.1

**Comment by CanRau** [comment]
maybe a version problem? i'm on 8.9.4
don't know how to check this right now, except for travis, maybe i can investigate it in the next days :)

**Comment by sladwig** [comment]
i think you are talking about node. npm stable is at 5.6.0, will dig a bit, too.

**Comment by CanRau** [comment]
right! my fault

**Comment by sladwig** [comment]
just tested again, linking locally and did work, then removed locally and reinstalled with npm and again works! so closing again

**Comment by CanRau** [comment]
interesting?!
glad you figured it out!
thanks for checking

and by the way, nice to see you around @sladwig 👍
